import jsPDF from "jspdf";
import autoTable from "jspdf-autotable";

export function generateCarbonReportPDF(company, emissions, aiInsights) {
  const doc = new jsPDF("p", "pt");
  const now = new Date();
  const dateStr = now.toLocaleDateString();

  doc.setFont("helvetica", "bold");
  doc.setFontSize(20);
  doc.setTextColor("#1A2E1A");
  doc.text("CarbonIQ Emissions Report", 40, 40);

  doc.setFontSize(11);
  doc.setFont("helvetica", "normal");
  doc.setTextColor("#111111");
  doc.text(
    `${company.name || "Your Organization"}  •  ${company.industry}  •  ${
      company.country
    }  •  Reporting year ${company.year}`,
    40,
    65
  );
  doc.text(`Generated on ${dateStr}`, 40, 82);

  doc.setDrawColor("#2C5F2D");
  doc.setLineWidth(1);
  doc.line(40, 90, 555, 90);

  const summaryTop = 115;
  doc.setFont("helvetica", "bold");
  doc.setFontSize(14);
  doc.text("Executive Summary", 40, summaryTop);

  doc.setFont("helvetica", "normal");
  doc.setFontSize(11);
  const score = emissions.carbonScore?.toFixed?.(0) ?? "-";
  const grade = emissions.grade || "-";
  const total = (emissions.totalTonnes ?? emissions.total)?.toFixed?.(2) ?? "-";
  const perEmployee = emissions.perEmployee?.toFixed?.(2) ?? "-";

  const summaryLines = [
    `Total emissions are ${total} tonnes CO₂e, corresponding to approximately ${perEmployee} tonnes per employee.`,
    `Your CarbonIQ score is ${score}/100 (grade ${grade}).`,
    `The largest source of emissions is ${emissions.biggestSource || "not yet determined"}.`,
  ];

  doc.text(summaryLines, 40, summaryTop + 24, { maxWidth: 515 });

  autoTable(doc, {
    startY: summaryTop + 80,
    head: [["Scope", "Emissions (t CO₂e)"]],
    body: [
      ["Scope 1", (emissions.scope1 ?? 0).toFixed(2)],
      ["Scope 2", (emissions.scope2 ?? 0).toFixed(2)],
      ["Scope 3", (emissions.scope3 ?? 0).toFixed(2)],
      ["Total", total],
    ],
    styles: { fontSize: 10 },
    headStyles: { fillColor: "#1A2E1A" },
  });

  const afterScopesY = doc.lastAutoTable.finalY + 30;

  if (aiInsights?.top3_recommendations) {
    doc.setFont("helvetica", "bold");
    doc.setFontSize(14);
    doc.text("Top Recommendations", 40, afterScopesY);

    const recRows = aiInsights.top3_recommendations.map((r, idx) => [
      `${idx + 1}. ${r.title}`,
      r.description,
      `${r.saving_tonnes} t`,
      `$${r.cost_saving}`,
    ]);

    autoTable(doc, {
      startY: afterScopesY + 12,
      head: [["Recommendation", "Description", "Estimated saving", "Cost saving"]],
      body: recRows,
      styles: { fontSize: 9, cellWidth: "wrap" },
      headStyles: { fillColor: "#2C5F2D" },
      columnStyles: {
        0: { cellWidth: 120 },
        1: { cellWidth: 220 },
        2: { cellWidth: 80 },
        3: { cellWidth: 80 },
      },
    });
  }

  const afterRecsY = doc.lastAutoTable?.finalY
    ? doc.lastAutoTable.finalY + 30
    : afterScopesY + 40;

  if (aiInsights?.industry_benchmark_analysis) {
    doc.setFont("helvetica", "bold");
    doc.setFontSize(14);
    doc.text("Industry Benchmark & Risk", 40, afterRecsY);

    doc.setFont("helvetica", "normal");
    doc.setFontSize(11);
    doc.text(aiInsights.industry_benchmark_analysis, 40, afterRecsY + 18, {
      maxWidth: 515,
    });

    if (aiInsights.risk_score) {
      doc.text(
        `Overall regulatory and transition risk is assessed as ${aiInsights.risk_score}.`,
        40,
        afterRecsY + 52,
        { maxWidth: 515 }
      );
    }
    if (aiInsights.risk_explanation) {
      doc.text(aiInsights.risk_explanation, 40, afterRecsY + 68, {
        maxWidth: 515,
      });
    }
  }

  let roadmapStartY = doc.lastAutoTable?.finalY
    ? Math.max(doc.lastAutoTable.finalY + 40, 420)
    : 420;

  if (aiInsights?.roadmap?.length) {
    doc.addPage();
    roadmapStartY = 60;

    doc.setFont("helvetica", "bold");
    doc.setFontSize(14);
    doc.text("12-Month Carbon Reduction Roadmap", 40, roadmapStartY);

    const roadmapRows = aiInsights.roadmap.map((step) => [
      `Month ${step.month}`,
      step.action,
      `${step.saving_tonnes} t`,
      step.cost,
      step.difficulty,
    ]);

    autoTable(doc, {
      startY: roadmapStartY + 16,
      head: [["Month", "Action", "Saving", "Cost", "Difficulty"]],
      body: roadmapRows,
      styles: { fontSize: 9 },
      headStyles: { fillColor: "#1A2E1A" },
      columnStyles: {
        0: { cellWidth: 60 },
        1: { cellWidth: 240 },
        2: { cellWidth: 70 },
        3: { cellWidth: 70 },
        4: { cellWidth: 70 },
      },
    });
  }

  const pageCount = doc.getNumberOfPages();
  for (let i = 1; i <= pageCount; i += 1) {
    doc.setPage(i);
    doc.setFontSize(9);
    doc.setTextColor("#64748B");
    doc.text(
      "Generated by CarbonIQ – AI Carbon Footprint Analyzer",
      40,
      doc.internal.pageSize.getHeight() - 30
    );
    doc.text(`Page ${i} of ${pageCount}`, 500, doc.internal.pageSize.getHeight() - 30);
  }

  doc.save(`CarbonIQ_Report_${company.name || "organization"}.pdf`);
}

